### ISSUE TITLE
Hur ska vi översätta publisher till svenska

### ISSUE THREAD

**Issue by matthiaspalmer** [DIGGSweden/DCAT-AP-SE#1]
Tidigare har vi kallat dcterms:publisher för "tillhandahållande organisation" vilket eventuellt är lite klumpigt. Man ser detta bland annat i listan av facetter på öppnadata.se. I menyn står istället "organisationer". I e-plikts dokumentationen från KB finns istället ordet "utgivare".
Enligt en tidigare diskussion har vi undvikit "ansvarig utgivare" då det har juridisk mening som man inte nödvändigtvis vill antyda. Man kan också tänka sig "utgivande organisation".

För att summera,  alternativen inkluderar:

- Tillhandahållande organisation (nuvarande)
- Utgivare
- Organisation
- Utgivande organisation 
- Ansvarig utgivare (kanske inte lämpligt)

**Comment by thomaskvist** [comment]
Hur är tankarna om man publicerar data via en annan part, t ex en kommun låter en region publicera  datamängden? Vill man inte veta kommunens namn? Men man kanske också vill vet vem som står för den praktiska delen av publicerandet. Kan ju påverka förtroendet om det kommunala datat publiceras av en part som somliga uppfattar som suspekt, t ex om en intresseorganisation publicerar ett urval av data från kommuner i syfte att stödja en viss agenda.

**Comment by bjornhagstrom** [comment]
Kan "Publicerare" vara ett alternativ?

**Comment by thomaskvist** [comment]
Tänker du  Björn på publicerare som den som väljer att publicera sina datat eller den som publicerar det praktiskt och gör datat tekniskt tillgängligt för nyttjare?

**Comment by bjornhagstrom** [comment]
Den som praktiskt gör det tillgängligt tänker jag. Den som väljer att publicera sitt data är väl ägaren/owner?

**Comment by mattiasekhem** [comment]
I [förklaringen till publisher](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/2012-06-14/?v=terms#publisher) står "Examples of a Publisher include a person, an organization, or a service." Tänker att det kanske ska heta "Tillhandahållande aktör" eller är det alltid en organisation? Tycker att Tillhandahållande organisation är tydligt.

**Comment by bjornhagstrom** [comment]
Jag tycker "Tillhandahållande aktör" är i linje med det du skrivit på andra issus Mattias och det är bra. Det enda jag kan fundera på är om det är lite klumpigt på samma sätt som det vi har idag och som Matthias utgår ifrån? I specifikationen har jag inga problem med det men om vi också ska använda samma termer när vi visar upp informationen på dataportalen (vilket jag tycker är en bra ambition) så ska det också fungera för den typen av målgrupp. 

Är det en ambition att ha enhetlig terminologi? Kanske en ny issue?

**Comment by bjornhagstrom** [comment]
PS Jag skulle nog vilja slå ett slag för "Publicrare" igen om det inte finns invändningar mot det?

**Comment by mattiasekhem** [comment]
Det [allmänna har särskilt ansvar för att svenskan används och utvecklas](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/spraklag-2009600_sfs-2009-600) och en utgångspunkt är ord som finns i svenska ordböcker vilket inte publicerare gör. Men ansvaret innebär som sagt också utveckling och med publicerare behöver man inte ta ställning till om det är en organisation eller person eller för den delen tjänst som publicerar något. Så jo jag är för Publicerare.

**Comment by MatsAhlin** [comment]
Risktermbanken föreslår Förläggare

**Comment by slyporks** [comment]
Undrar om "förmedlare" kan vara ett alternativ.

**Comment by matthiaspalmer** [comment]
Efter mycket diskussion står sig utgivare fortfarande rätt bra.
Om frågan aktualiseras igen med ett bättre förslag får ärendet öppnas igen.
Här finns en rekommendation för att särskilja utgivare från andra aktörsroller:
https://diggsweden.github.io/DCAT-AP-SE/docs/recommendations.html#9-utgivare-producent-och-andra-akt%C3%B6rsroller
