### ISSUE TITLE
Hur ska datatjänster presenteras på dataportalen

### ISSUE THREAD

**Issue by matthiaspalmer** [diggsweden/DCAT-AP-SE#104]
### What benefits does the suggestion solve?

Det finns en risk att med introduktion av datamängdsserier det blir många mindre datamängder vars enda syfte är att exponera en fil. Sådana datamängder kan göra det svårt att hitta på dataportalen.

### Feature suggestion description

Det finns i huvudsak två perspektiv.
1. Visa alla datamängder obereonde om de är datatjänster, del av datatjänster eller vanliga datamängder (detta motsvarar en fortsättning från där vi är idag).
2. Dölj datamängder som hör till en datamängdsserie, kanske kontrollerat via ett filter.

**Comment by matthiaspalmer** [comment]
Förslag är att vi siktar på alternativ 2 och därmed:
1. Siktar på att erbjuda ett filter för att dölja datamängder som ligger i datamängdsserier på dataportalen. Skapar en listning av datamängder på datamängdsseriens landningssida samt länkar från datamängder som ingår i serier till motsvarande datamängdsserie. Detta bör bli översättas till ett uppgift till dataportalens vidare utveckling.
2. förtydligar på sidan [Metadata på dataportalen](https://docs.dataportal.se/dcat/docs/dataportal/) hur datamängder som ligger i datamängdsserier kommer vara dolda per default.

**Comment by salgo60** [comment]
### Ni måste ha bättre koppling till datakvalitet och semantisk interoperabilitet

Arbeta aktivt med den... idag är det mer **den som laddar upp är ansvarig** --> blir massa datasilos och blir helt galet när [DIGG själva skickar runt massa textsträngar](https://github.com/diggsweden/DCAT-AP-SE/issues/72#issuecomment-2081538484)...
* kunskapsgrafer som grunden för det som skall levereras --> knyter ihop dataset och leverantörer -  **idag ser jag datasilos** - DIGG som laddar upp ett dataset måste ha en persistent identifierare som sedan kan identifieras på EDP
   * Dataportalens koppling till Europeiska dataportalen (EDP) - se hur galet det blir om saker skickas till EDP inte ens DIGGs egna dataset kan man som konsument förstå vad det är [diggsweden/DCAT-AP-SE/issues/72#issuecomment-2081538484](https://github.com/diggsweden/DCAT-AP-SE/issues/72#issuecomment-2081538484)
      * Öppen data är internationellt blir helt galet då det inte skapas [tydliga DOI som uttrycker om datat är samma på olika portaler](https://github.com/diggsweden/DCAT-AP-SE/issues/72)
      * samma med termkataloger med ansvariga som används av alla även utanför Sverige jmf hur fel dataverkstaden arbetar [#32](https://github.com/salgo60/Anslagstavla/issues/32) / [DIGG #72](https://github.com/salgo60/DIGG-skuggbacklog/issues/72) / [ESV #7](https://github.com/salgo60/ESV-skuggbacklog/issues/7)  
   * detta skall kopplas till ett ekosystem se [The Magnus List](https://www.wikidata.org/wiki/User:Salgo60/ExternalIdentifiers#The_Magnus_List)
   * det skall finnas modeller för [cocreation #776](https://github.com/salgo60/DIGG-skuggbacklog/issues/776)
* beskriva datamängderna inte i pdf dokument utan med ex. ShEx jmf [#129 svenska riksdagsmän E395](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/129)
* visa upp vilka som använder datat och att datakvaliten blir bättre jmf [wikidata som har grafana](https://github.com/salgo60/DIGG-skuggbacklog/issues/76#issuecomment-1560707265)

<img width="1051" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/4576283f-3ed2-4254-b2b1-0daae1d3e78f">

**Comment by matthiaspalmer** [comment]
Nu finns en förtydling:

[Sektionen: Datamängdsserier på dataportalen](https://docs.dataportal.se/dcat/docs/dataportal/#datamangdsserier-pa-dataportalen)
