### ISSUE TITLE
Ta fram en rekommendation för lämplig uppdateringsfrekvens för datamängdsserier

### ISSUE THREAD

**Issue by matthiaspalmer** [diggsweden/DCAT-AP-SE#111]
### What benefits does the suggestion solve?

Det ska vara tydligt för dataportalen om den kan förväntas sig några tiotal datamängder i en datamängdsserie eller om det kan vara tusentals.

### Feature suggestion description

Tydliggör när det är lämpligt att förvalta data i en datamängdsserie:
- När nya filer tillkommer månatligen?
- Dagligen eller ännu oftare?
- Närhelst det sker en manuell process?
- När det är viktigt att ange metadata för att förtydliga något?

Ett förslag är att det ska vara behovsdrivet, men inte mer än 100 datamängder i en dataserie.
Beskriv också i rekommendationen vad man gör om man har behov som inte passar i en datamängdsserie, hur man går till väga då. T.ex:
- dcat:accessURL till en webbfolder?
- Paketera som en zip
- Slå samman data, dvs uppdatera en fil som växer
- Bygga system och peka ut API istället?

**Comment by matthiaspalmer** [comment]
Förslag:

Vi rekommenderar att om man har en datamängdsserie som i huvudsak har en temporal dimension att man inte har en uppdateringsfrekvens som är mer frekvent än en gång i månaden. Dvs man inte lägger till nya datamängder till serien oftare än en gång i månaden.

**Comment by salgo60** [comment]
Blir det inte bara konstigt att hitta på generella regler... är det Riksbankens styrränta skall saker uppdateras direkt gissar jag... gissar att hela tanken med en dataportal är lite föråldrat om man strävar efter att jobba datadrivet....
* fokusera på [persistenta identifierare för dataset och organisationer](https://github.com/diggsweden/DCAT-AP-SE/issues/72)
* att det finns [best practice ](https://github.com/diggsweden/persistent-identifiers-investigation/issues/4)hur man supportar ett ekosystem
   * att [logga fel](https://github.com/salgo60/DIGG-skuggbacklog/issues/50) med publika öppna backlogs
   * [arbeta ihop](https://forum.jobtechdev.se/t/har-ni-input-till-varens-meetups/263/3)

**Comment by matthiaspalmer** [comment]
Nu är två rekommendationer framtagna som är relevanta för denna issue:

[Rekommendation 17 - Antalet datamängder i en datamängdsserie](https://docs.dataportal.se/dcat/docs/recommendations/#17-antalet-datamangder-i-en-datamangdsserie)
och
[Rekommendation 19 - Alternativ till datamängdsserier](https://docs.dataportal.se/dcat/docs/recommendations/#19-alternativ-till-datamangdsserier)

**Comment by salgo60** [comment]
**Fundering:** Är det inte mer dataportal produktens begränsningar som styr än vad som skapar bra data?

<img width="748" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/9fbc141e-17fe-48eb-8707-1aaacbb7f0ae">

Borde vara enkelt att ställa en SPARQL fråga som hämtar allt som har 
* med en viss datamängd oberoende av år och land dvs. [federated SPARQL med EDP](https://data.europa.eu/en/about/sparql) borde enkelt kunna stödjas
* är tanken fortfarande att alla dataserier skall skickas upp till **EDP och hur tänker dom har dom samma begränsningar**?

**Comment by salgo60** [comment]
> Att ha tusentals datamängder i en datamängdsserie låter som ett dåligt beslut. Det är därför som rekommendation 19 finns.

Tackar för svar förstår inte hur ni resonerar...

Gissat att med ett vettigt frågespråk som SPARQL så kan alla datamängder hämtas.... 
* jag testade nyss [Riksarkivets försök att ladda upp zipfiler](https://github.com/salgo60/Svenskaforsamlingar/issues/54) som sedan skall innehålla datat vilket känns som en väg framåt men zipfiler och csv filer har sina problem
  * dock en fördel att samma request hämtar allt....

Vore kanske bättre att jobba på ett Change stream API modell det Wikidata har 
* [API Recent_Changes_stream](https://www.wikidata.org/wiki/Wikidata:Data_access/sv#Recent_Changes_stream)
* exempel websida byggt med detta https://tools.wmflabs.org/wikidata-todo/rcvis.html

<img width="1111" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/3bf9fe82-8760-49dd-b1b0-018cd04ed8e8">

* sida att testa olika change streams

<img width="1411" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/e5a96a8c-5d62-420d-80a1-25f21942825b">
