### ISSUE TITLE
Med bidrag från "Kristine Ulander - Myndigheten för digital förvaltning"

### ISSUE THREAD

**Issue by salgo60** [diggsweden/DCAT-AP-SE#113]
### Contact Details

Magnus Sälgö

### What happened?

Person med koppling organisation som inte gäller anges med textsträngar där varken person eller organisation har persistent unik identifierare. När personen nu inte arbetar kvar på nämnda organisation så blir det rörigt vilket måste vara ett tecken på bug och **feltänk av en digital expertmyndighet**

### Steps To Reproduce

* https://docs.dataportal.se/dcat/sv/ DCAT-AP-SE version 3.0.0 - 8 Mars 2024

<img width="1163" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/36b0d96a-29d7-4c57-9784-58c6335262db">

Inte heller myndigheterna har persistenta identifierare i specifikationen, vilket har flaggats i andra skuggbackloggar [#19](https://github.com/salgo60/ESV-skuggbacklog/issues/18)  (exempel på [community projekt att skapa detta- myndighetsdata](https://github.com/civictechsweden/myndighetsdata), [handlingar.se försök](https://github.com/civictechsweden/myndighetsdata/issues/1)). 
* tycker DIGG specifikationer som detta bör ha ett dataset med metadata vilka myndigheter som deltar och vilka kommuner/myndigheter som deltar, att alla klasser relationer egenskaper redovisas med stöd för andra språk än svenska... .... 
  * vi ser samma [dåliga metadata på Esam-dokument](https://github.com/salgo60/LagrummetLight/issues/2) 
     * exempel hur vi löser det i Wikidata 
         * dokument [Q112766254 Myndigheters användning av sociala medier](https://www.wikidata.org/wiki/Q112766254?uselang=sv)
         * grupp [E-delegationen Q98591131](https://www.wikidata.org/wiki/Q98591131?uselang=sv)

### What did you expect?

Personer identifieras unikt dvs. [FAIRDATA F1](https://www.go-fair.org/fair-principles/f1-meta-data-assigned-globally-unique-persistent-identifiers/) och [5 star open data](https://5stardata.info/en/) skapas och att det finns metadata så man kan se vilka som deltar i vilka utredningar, vilka utredningar som refererar andra utredningar vilka myndigheter som är aktiva och vilka krav dom har i olika utredningar jmf [citation graphs](https://github.com/salgo60/DIGG-skuggbacklog/issues/85) ex. [Myndigheters användning av sociala medier](https://www.esamverka.se/download/18.1d126bc174ad1e6c39c6df/1464273265830/Riktlinjer%20f%C3%B6r%20myndigheters%20anv%C3%A4ndning%20av%20sociala%20medier%201.0.pdf) --> [citation graphs](https://w.wiki/5NGk)

<img width="1059" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/37e05255-9d71-442a-9431-33da700fe6f3">

<img width="966" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/ee1e04bb-01ed-4457-8546-9213ca361f08">

<img width="1024" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/12a5d819-899b-4527-9c8f-e220ee1132cf">

* se [DIGGs utredning Persistenta Identifierare](https://github.com/diggsweden/persistent-identifiers-investigation/issues/19) där detta inte styrdes upp nu skapas nya versioner av specar där man inte verkar veta att den vänstra handen rekommenderar PID:ar medans den högra skapar otydliga textsträngar....
* ESV valde att personer som skickar in remissvar anonymiseras vilket känns enormt ovisionärt och kontraproduktivt - [FAIRDATA F1: ESV Persistenta identifierare för personer](https://github.com/salgo60/ESV-skuggbacklog/issues/8)
* [Riksarkivet pekar 2018 i sin slutrapport](https://riksarkivet.se/media/pdf-filer/slutrapport-regeringsuppdrag-riksarkivet-180627.pdf) på att persistenta Unika Identfierare(PID) [är en förutsättning för att man skall kunna skapa länkar i ett nätverk](https://github.com/Riksarkivet/dataplattform/issues/17#issuecomment-1576627510)
  * 2023 kan dock inte Riksarkivet hantera PID:ar i sina API:er
    * [2023 dec 22 anser DIGG](https://github.com/diggsweden/persistent-identifiers-investigation/issues/23#issuecomment-1867537191) att dom _inte_ skall utrycka att Riksarkivet är en del av att se till att PID:ar finns åtkomliga för myndigheters arkiverade information...  känns som ett **moment 22** särskilt när DIGG själva inte verkat "[built a culture for data citation](https://www.researchgate.net/figure/Model-for-a-culture-of-data-citation_fig3_307547241)"

#### Fattigmanslösning
Fattigmanslösning om DIGG inte kan skapa egna persistenta identifierare är att kräva [ORCID](https://orcid.org/0000-0003-2568-267X) av personer som deltar i en utredning se förslag [NOSAD #83](https://github.com/salgo60/DIGG-skuggbacklog/issues/83) / att kunna skapa [citation graphs av statens dokument där specar som detta är en kandidat #85](https://github.com/salgo60/DIGG-skuggbacklog/issues/85) / [Citation graphs och 5 stardata saknas](https://github.com/salgo60/DIGG-skuggbacklog/issues/85)

[DIGG har pratat om](https://github.com/diggsweden/DCAT-AP-SE/issues/93#issuecomment-1814326101) att dom skall städa upp sina projekt så man ser att folk slutat och förhoppningsvis vilka roller personer/konsulter har hos DIGG i olika projekt - status?

![image](https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/c8fa92ef-c58d-4fe6-8a9f-c1243de5bef7)

* sidan 16 [DOI: 10.2830/59387](https://data.europa.eu/doi/10.2830/59387) - Data citation A guide to best practice - Publications Office of the European Union

<img width="683" alt="image" src="https://user-images.githubusercontent.com/14206509/199216141-34146f14-ac6a-4393-b6b8-26f810f554e0.png">

### Version

-

**Comment by matthiaspalmer** [comment]
Vi uppdaterar listan.

**Comment by salgo60** [comment]
Ok blir galet att [ni lägger ned 6 månader att speca persisteta identfierare](https://github.com/diggsweden/persistent-identifiers-investigation/graphs/contributors) och när dom skall användas praktiskt så blir det textsträngar... stänger denna...
