### ISSUE TITLE
Förtydliga om hur man lägger upp flera filer till en distribution

### ISSUE THREAD

**Issue by matthiaspalmer** [DIGGSweden/DCAT-AP-SE#17]
Som specifikationen ser ut nu kan man upprepa dcat:dowloadURL för att peka på flera filer, t.ex. en fil med data per kvartal. Det är ett sätt att skapa tidsserier.

Vi skulle kunna stödja ytterligare metadata för filen (URL:en) också, t.ex. en dcterms:title och dcat:issued för att göra det möjligt att se en tidsserie som inte bara är baserad på information inkodat i URL:en.

Notera att även dcat:accessURL är tillåten att upprepas, men det är snarare ett sätt att peka på olika likvärdiga accesspunkter än data uppdelat i en tidsserie.

**Comment by matthiaspalmer** [comment]
Se diskussionen om [upprepning av dcat:downloadURL](https://github.com/w3c/dxwg/issues/868).

**Comment by bjornhagstrom** [comment]
Jag tycker det vore en bra idé.

**Comment by matthiaspalmer** [comment]
Det finns nu en rekommendation kring denna fråga här:
https://diggsweden.github.io/DCAT-AP-SE/docs/recommendations.html#4-vissa-datam%C3%A4ngder-delas-med-f%C3%B6rdel-upp-i-flera-filer
