### ISSUE TITLE
Hur översätter vi foaf:Agent till svenska

### ISSUE THREAD

**Issue by matthiaspalmer** [DIGGSweden/DCAT-AP-SE#21]
I nuvarande DCAT-AP används foaf:Agent enbart via dct:publisher vilket gör det möjligt att namge utifrån den rollen (t.ex. tillhandahållande organisation, se #1 ). Men när nu antalet möjliga roller för foaf:Agent ökar, t.ex. via dct:creator (se #20 ) så ökar behovet att tala om foaf:Agent på ett självständigt sätt, precis som datamängd eller katalog.

Så vad kallar vi en foaf:Agent på svenska, kanske aktör?

**Comment by carwash** [comment]
På mötet 2019-09-30 var det lite snack om hur organisationer skulle kunna identifieras kopplat (tror jag) den här issue:n. Specifikt nämndes något om identifierare som skulle kunna tilldelas av KB med organisationsnummer som "slug". Där finns det dock problem med aktörer som delar samma organisationsnummer.
Varför inte helt enkelt använda organisationens basdomän som identifierare (URI) i LOD-andan? Eller en avdelnings- enhetens URI under domänen om man behöver vara så specifik. Riksarkivet skulle t.ex. vara `<http://www.ra.se/>`. Vill man ha en koppling till organisationsnummer kan man väl ange detta i ett RDF-dokument på den URI:n som levereras till användaragent som kan acceptera den (tillsammans med andra beskrivande foaf:-uppgifter). Eller?

**Comment by mattiasekhem** [comment]
Aktör är bra. (Enligt [svensk ordbok](https://svenska.se/so/?id=00539&pz=7) "person eller part som agerar" och enligt [Vägledning för digital samverkan](http://www.esamverka.se/download/18.7e784787153f0f33aa51c876/1464274862194/V%C3%A4gledn%20digital%20samverkan%204.1.pdf) "människa eller organisation som agerar i samverkan"

**Comment by matthiaspalmer** [comment]
Bra att vi är överens om aktör.

Nästa fråga:
I DCAT-AP2 finns nu ett sätt att peka ut aktörer med en mängd olika relationer utöver publisher och creator. Från en datamängd pekar använder man propertyn prov:qualifiedAttribution för att peka på en prov:Attribution som i sin tur har en dcat:hadRole och en prov:agent. I RDF ser strukturen alltså ut som följer:

```
dataset1  prov:qualifiedAttribution _:b1 .
_:b1 rdf:type prov:Attribution ;
        dcat:hadRole inspire:custodian ;
        prov:agent ex:agent1 .
ex:agent1 foaf:name 'Öppna organisationen' .
```
Frågan är hur vi namnger qualifiedAttribution / Attribution och hadRole på svenska.
Så här skulle det kunna se ut i ett formulär:

```
Erkännande:
   Roll:  Custodian
   Aktör:  Öppna organisationen

```
Dvs är "erkännande" bra för att summera qualifiedAttribution och Attribution respektive "roll" för dcat:hadRole. Om inte, har vi några bra alternativ?

**Comment by MatsAhlin** [comment]
Rikstermbanken föreslår Agent även på svenska

**Comment by bjornhagstrom** [comment]
Det står ju "hadRole" vilket signalerar att det kan skilja sig från "hasRole"? Det bör nog speglas i den svenska versionen också om inte annat för framtidssäkring. Hur beskrivs dessa fält på engelska?

**Comment by matthiaspalmer** [comment]
För att summera:
Vi använder aktör som generellt ord för foaf:Agent klassen.
När man pekar på en aktör via prov:qualifiedAttribution använder vi då "övrig aktör" för att särskilja från "utgivare" och "producent" som finns som separata fält på samma nivå. I själva attribution instansen har man två fält, ett fält för roll och ett fält som vi helt enkelt benämner "aktör" för att peka på den aktör som agerar i den rollen.
