### ISSUE TITLE
Ska vi ha en rekommenderad förteckning av licenser

### ISSUE THREAD

**Issue by matthiaspalmer** [diggsweden/DCAT-AP-SE#22]
I tyskland har man tagit fram en lista med välkända licenser för att förenkla för organisationerna:
https://www.dcat-ap.de/def/licenses/

Det finns en mer omfattande lista med licenser här:
https://spdx.org/licenses/

Både Tyskland och spdx myntar nya URI:er för licenser, t.ex. använder ingen av dem de etablerade URI:erna för CC licenserna, t.ex:
http://creativecommons.org/licenses/by/4.0/

**Comment by carwash** [comment]
Tycker det vore bra att ha en förteckning som folk kan förhålla sig till, men dumt att mynta nya URI:er där licenserna redan har välkända URI:er med bred tillämpning.
I K-samsök tillåter vi ett [begränsat antal licenser](https://www.raa.se/hitta-information/k-samsok/att-anvanda-k-samsok/rattigheter/) som är en delmängd av [de som Europeana tillämpar](https://pro.europeana.eu/page/available-rights-statements). Dessa listor är nog för restriktiva för DCAT-AP-SE, men någonting i den stilen med flera välkända licenser vore önskvärd.

**Comment by matthiaspalmer** [comment]
Om vi gör detta bör det vara med hjälp av Publication office vokabulär, se #100 istället.
