### ISSUE TITLE
Gör det möjligt att associera goda exempel - showcases

### ISSUE THREAD

**Issue by matthiaspalmer** [diggsweden/DCAT-AP-SE#25]
När en datamängd väl börjar användas är det intressant för andra att se exempel på detta.
Dataägaren kanske vill peka ut vad som gjorts, vem som gjort något och omfattningen.

Ett exempel / showcase kan vara en app, en webbsite, en visualisering, en analys osv.
Ofta vill man peka ut en resurs som är tillgänglig någon annanstans, formen kan vara en hel webbapplikation eller en bloggpost som berättar mer.

En lösning är att använda en "qualified relation" i DCAT 2 för att åstadkomma detta.

**Comment by thomaskvist** [comment]
En utmärkt idé. Med tanke på de tekniska lösningarnas förgänglighet bör man också kunna hänvisa till någon form av dokument eller video som beskriver lösningen. Även användning i appar som inte längre är aktiva kan ju utgöra ett användningsexempel av intresse.

**Comment by matthiaspalmer** [comment]
Löses som en del av #106.
