### ISSUE TITLE
Gör det möjligt att peka på förslag till användning

### ISSUE THREAD

**Issue by matthiaspalmer** [diggsweden/DCAT-AP-SE#26]
För att uppmuntra användning av datamängder kan dataägaren (eller någon annan) ge förslag på tillämpningar. Ett sådan förslag behöver innehålla en kortare beskrivning som förtydligar vad som är tanken och hur datamängden. Ett förslag bör kunna kopplas ihop med flera datamängder.

Man kan tänka sig att använda "qualified relation" i DCAT 2 för att skapa relationen.

**Comment by aidig** [comment]
[duv:hasUsage](https://www.w3.org/TR/vocab-duv/#Property:hasusage) fra [Data on the Web Best Practices: Dataset Usage Vocabulary](https://www.w3.org/TR/vocab-duv/) kunne også være et forslag (vi overvejer fx at anvende denne egenskab i DCAT-AP-DK 2.0)

**Comment by salgo60** [comment]
jmf Wikidata [GITHUB Topics Property P9100](https://www.wikidata.org/wiki/Property:P9100)

**Comment by matthiaspalmer** [comment]
Löses som en del av #106.
