### ISSUE TITLE
Associera representativa bilder till en datamängd

### ISSUE THREAD

**Issue by matthiaspalmer** [diggsweden/DCAT-AP-SE#27]
Presentation av datamängder på en site som öppnadata.se kan behövas kompletteras med bilder för att göra utforskningen mer lättillgänglig. Det är notoriskt svårt att automatiskt skapa visualiseringar av datamängder för en site som öppnadata då det skulle kräva:

1. Att man laddar iallafall delar av datan
2. Vet hur man ska bearbeta den och generera visualiseringar

Med största sannolikhet skulle sådana automatskapade bilder bli både fula och orepresentativa.

En bättre lösning vore att ge dataägare möjlighet att associera en eller flera bilder till en datamängd som de tycker är representativ. Det kan vara en tematisk bild eller en visualisering man själv gjort av datat.

**Comment by kristineulander** [comment]
Har du sett exempel på andra länder som har detta och isåfall hur det sett ut?

**Comment by matthiaspalmer** [comment]
Tyvärr inte, men inte haft tid att kolla runt på alla portaler i Europa.

Däremot har vi sett behovet från enskilda dataproducenter som vill lyfta fram datamängder på ett rikare sätt på sin egen webb. Skatteverket är ett sådant exempel. Den temporära lösningen ett manuell arbete i den meningen att de skapat redaktionellt innehåll för några utvalda datamängder som de beskriver separat från själva förteckningen.

**Comment by matekh** [comment]
Behöver man också fundera på tillgänglighet t ex syntolkning av bilden och annan metadata kring bilden?

**Comment by matthiaspalmer** [comment]
Löses som en del av #106.
