### ISSUE TITLE
Svensk version på engelska? :)

### ISSUE THREAD

**Issue by bjornhagstrom** [diggsweden/DCAT-AP-SE#29]
Det kommer inte bara vara svenska utvecklare som vill implementera specen eller förstå metadata. Hur gör vi det begripligt för dem? Det kanske finns en engelsk version av det som är ändrat från originalversionen som jag bara inte sett efter en snabb koll?

**Comment by bjornhagstrom** [comment]
Vi kanske ska ha sammanfattning av ändringar på engelska och noteringar på fältnivå med förändringar?

**Comment by matthiaspalmer** [comment]
I dagsläget finns bara metadataspecifikationen på [svenska](https://metasolutionsab.github.io/DCAT-AP-SE/sv/) och [engelska](https://metasolutionsab.github.io/DCAT-AP-SE/en). En tabell med vilka ändringar som föreligger mot DCAT-AP är inte framtagen ännu. Det vore nog trevligt att ha en sådan förteckning.
Den kommer dock vara stadd i förändring under en tid så jag föreslår att om det prioriteras att vi gör en sådan förteckning när vi kommit längre (och när nästa version av DCAT-AP släppts).

**Comment by bjornhagstrom** [comment]
Jag ser din poäng. Fördelen med att göra detta allt eftersom man gör förändringar är att det är lätt att missa något om man gör det i efterhand. Å andra sidan är det nog lätt att göra det under tiden också...

Frågan är om man ska ha den svenska versionen med anpassningar av det engelska originalet på engelska i sin helhet också? Det kanske är att gå för långt men jag tror det är viktigt med enkelhet och tydlighet kring vad som ändrats så vi kan behöva fundera på hur detta ska visas.

**Comment by MariaSoderlind** [comment]
Känns som om det är dags att ta fram tabellen med vilka ändringar som föreligger mot DCAT-AP nu. Jag kan tycka att den borde finnas framme före nya versionen släpps, så att alla på marknaden har samma möjlighet att se ändringar och kunna vara snabba med att anpassa sina produkter

**Comment by matthiaspalmer** [comment]
@MariaSoderlind En sådan tabell med ändringar är under framtagande. Den kommer definitivt finnas tills den nya versionen släpps.
