### ISSUE TITLE
Koppling mot arkivförteckning

### ISSUE THREAD

**Issue by bjornhagstrom** [DIGGSweden/DCAT-AP-SE#30]
I Riksarkivets arbete fanns ett bra och viktigt fokus på att se till att man kunde skapa psi-förteckning och arkivförteckning med en enda insats och inte behövs dubbeljobba. Är detta en ambition vi fortfarande har? Hur säkerställer vi då detta?

**Comment by almalander** [comment]
Viktig ambition. Riksarkivets föreskriftsrätt är begränsad till statliga myndigheter, men kommuner och regioner brukar följa Riksarkivet i möjligaste mån.
Om vi vill arbeta med detta (dvs arkivförteckning med inkluderad PSI) borde Riksarkivet vara delaktigt i arbetet, tillsammans med SKL.

**Comment by matthiaspalmer** [comment]
Se ärende #3 .

**Comment by matthiaspalmer** [comment]
Jag föreslår att vi skriver en rekommendation för hur man ska göra för att ange relationen till arkiv. Rekommendationen skulle kunna innefatta följande information:

Om vi kallar åtkomst till en datamängd som inte sker via arkivsystem för **primär åtkomst** kan vi identifiera fyra huvudsakliga situationer som kan uppkomma med hänsyn till arkivredovisningar:
 
1. Datamängden arkiveras inte och har ingen primär åtkomst.
2. Datamängden arkiveras inte men har primär åtkomst.
3. Datamängden arkiveras och har primär åtkomst.
4. Datamängden arkiveras men har ingen primär åtkomst.

Alternativ 1 motsvarar att datamängden beskrivs i PSI-förteckningen utan någon distribution med accessRight satt till non-public.

Alternativ 2 motsvarar datamängder utan arkiv koppling, inget speciellt gäller därmed ur arkivperspektivet.

Vid alternativ 3 lägger man till en distribution som motsvarar åtkomst till datamängdens arkiv version och vid alternativ 4 är det den enda distributionen som finns. I båda situationerna  kan man använda adms:identifier på datamängds nivån (som kallas "other identifier") för att peka ut närmaste nivå i arkivredovisningen (betecknas förvaringsenhet).

**Comment by UlrikaDMattsson** [comment]
Alla offentliga datamängder är handlingar och ska eventually arkiveras. Därför är det absolut ett önskemål och vore en effektivisering om vi kan koppla arkivförteckningen på ngt sätt och slippa ha dubbla förteckningar. Kan ni se den här mappningen? [
![Begreppsmodell öppen och säker informationshantering](https://user-images.githubusercontent.com/57920740/69095544-daa40600-0a52-11ea-9ee5-4279ef5fdddd.png)
](url)

**Comment by matthiaspalmer** [comment]
En rekommendation kring hur man kopplar till en arkivförteckning finns nu här:
https://diggsweden.github.io/DCAT-AP-SE/docs/recommendations.html#5-att-koppla-samman-en-datam%C3%A4ngd-med-en-arkivredovisning

Utifall denna rekommendation inte är tillräcklig får ärendet öppnas igen.
