### ISSUE TITLE
önskemål om testmiljö och dokumentation

### ISSUE THREAD

**Issue by MichaelOstling** [DIGGSweden/DCAT-AP-SE#31]
Det vore bra om det fanns en testmiljö som det vara möjligt att publicera till
I nuläget måste man publicera in till den skarpa miljön för att fullt ut se hur informationen som publiceras ser ut presentationsmässigt och hur sökkriterierna finns olika delar av det som publiceras.

Just nu går det att genomföra själva valideringen i sandboxen, men man vet inte hur presentationen blir. 

Det vore bra med en dokumentation om hur varje RDF-element presenteras och vilka element som är sökbara och på vilket sätt.

Detta vore bra att information ca 3 månader innan release så vi har möjlighet att anpassa innehållet i vår transformering till DCAT som genomförs.

**Comment by mattiasekhem** [comment]
Förstår behovet av en testmiljö och det behövs en del beräkning och ställningstagande eftersom det är kostnader förknippat med det. Arbete planeras för det!

**Comment by matthiaspalmer** [comment]
Dokumentation om testmiljö finns nu på:
https://diggsweden.github.io/DCAT-AP-SE/docs/dataportal.html
