### ISSUE TITLE
Hur "interoperabla" är olika profiler med varandra

### ISSUE THREAD

**Issue by MichaelOstling** [DIGGSweden/DCAT-AP-SE#32]
Mer en nyfiken fråga än en åtgärd i vår profil.

Hur "interoperabla" är olika profiler av DCAT-AP  
ex DCAT i relation till DCAT-AP och 
DCAT-AP till DCAT-AP-SE och DCAT-AP-NO? 
En profil är ju normalt ett subset av en standard.

Kan man kommunicera mellan DCAT-AP och en DCAT-implementering i Nordamerika 
eller 
kan ( som exempel) den Svenska, Norska och Danska profilen kommunicera med varandra?
Finns det element som hanteras helt olika av respektive land?

Finns denna typ av krav med vid anpassning/utveckling av profilen?

**Comment by matthiaspalmer** [comment]
Detta är nu förklarat här:
https://diggsweden.github.io/DCAT-AP-SE/docs/standards.html#interoperabilitet-mellan-olika-profiler
