### ISSUE TITLE
Ambitionsnivån / Omfattning

### ISSUE THREAD

**Issue by slyporks** [DIGGSweden/DCAT-AP-SE#33]
Det känns viktig att ha en tydlig bild av det DCAT-AP-SE kommer att användas till, utöver det som idag hanteras på oppnadata.se

Behöver vi hantera avgiftsbelag data, begrepp, information om tjänster?

Referera till #18 (Data Service) & #23 (Terminologier)

**Comment by kristineulander** [comment]
Yes DCAT-AP ska hantera ett bredare scope av data, närmare besämt "PSI-data" som ska in i "PSI-förteckningen" enl PSI-lagen. Det innebär "typer av handlingar som vanligen kan tillhandahållas elektroniskt för vidareutnyttjande". Avses både det som är:
1) Öppna data (data som är helt fri att använda utan några som helst villkor som t ex upphovsrätt eller avgifter m.m.
2) Data som kan användas men med vissa restriktioner eller villkor som till exempel upphovsrätt, avgifter m.m.

Med nya Data-services möjligheten i DCAT-AP kan även information om tjänster ingå, vilket vi ser är av värde då det i dagslägen blandas i sökresultaten. Data-services funktionaliteten möjliggöra även förbättra möjligheter att beskriva API´er, något som har varit en issue fram tills nu.

**Comment by kristineulander** [comment]
Ja DCAT-AP ska hantera data som ingår i PSI-lagens "PSI-förteckning". 
PSI-förteckningen ska innefatta alla typer av handlingar som vanligen kan tillhandahållas elektroniskt för vidareutnyttjande, avses både det som är:
1) Öppna data (data som är helt fri att använda utan några som helst villkor som t ex upphovsrätt eller avgifter m.m.
2) Data som kan användas men med vissa restriktioner eller villkor som till exempel upphovsrätt, avgifter m.m.

Data services möjliggör även en förbättrad möjlighet att beskriva APIér, vilket tidigare har saknats. Data services öppnar dock upp också möjligheten för att separera datamängder från data-tjänster, vilket skulle ge stort värde. I dagsläget blandas tjänster och datamängder vilket är problematiskt för användarna.

**Comment by Kjellhjorth** [comment]
Känns viktigt att vi tydliggör vad ÖD-portalen ska supportera, funktionalitet, mm och utifrån det perspektivet tittar på vilka metadata som behövs.

**Comment by matthiaspalmer** [comment]
En introducerande text är framtagen som beskriver detta:
https://diggsweden.github.io/DCAT-AP-SE/docs/introduction.html
