### ISSUE TITLE
Relationen till BReg-DCAT-AP

### ISSUE THREAD

**Issue by slyporks** [DIGGSweden/DCAT-AP-SE#34]
Hur ska vi förhålla oss till BReg-DCAT-AP specifikationen och inkorporeringen av delar av Core Voc i modellen?
https://joinup.ec.europa.eu/solution/abr-specification-registry-registries/document/specification-registry-registries-version-meeting-september

**Comment by matthiaspalmer** [comment]
Senaste [ABR mötet](https://joinup.ec.europa.eu/solution/abr-specification-registry-registries/news/save-date-wg-24-oct) gav viss klarhet i hur man tänkt att de olika delarna från Core Voc ska användas. Framförallt handlar det om "Public Service" klassen som ska förstås som att t.ex. skatteverket erhåller tjänsten att deklarera via post eller online (olika kanaler).

Att utvidga den svenska DCAT-AP med denna information skulle innebära att öppnadata.se skulle kunna agera som en nationell "tjänstekatalog" utöver att den redan är en nationell "datakatalog". 
Efter diskussion med DIGG är beslutet att detta är intressant och möjligt men i dagsläget inte prioriterat. Att det inte är prioriterat beror på två saker:

1. Det ligger inte inom det nuvarande uppdraget.
2. BReg-DCAT-AP behöver troligtvis mogna.

Notera att inkorporera Breg-DCAT-AP i den svenska profilen inte skulle påverka funktionalitet, det skulle bara ge fler möjligheter. MEN, då BReg-DCAT-AP i dagsläget inte är tillräckligt mogen för att accepteras rakt av skulle det innebära en del jobb som eventuellt skulle göras ogjort om BReg-DCAT-AP ändras framöver. Detta är särskilt tydligt när man ser hur DCAT2 medför möjligheter som inte verkar ha slagit igenom ännu i modellen för BReg-DCAT-AP, t.ex. att Public Service klassen skulle kunna vara en dcat:Resource vilket kräver en dialog med gruppen som jobbar med Core Voc för att kunna genomföras.

**Comment by matthiaspalmer** [comment]
Relationen till BReg-DCAT-AP är beskriven här:
https://diggsweden.github.io/DCAT-AP-SE/docs/standards.html#relation-till-breg-dcat-ap
