### ISSUE TITLE
Indikation om avgift

### ISSUE THREAD

**Issue by matthiaspalmer** [diggsweden/DCAT-AP-SE#4]
Riksarkivet föreslog användningen propertyn gr:hasPriceSpecification för att ange:

```
Avser information som ska kunna ge svar på följande frågor:
− Finns det avgifter kopplade till datamängden?
− Om ja, vilken beräkningsgrund gäller?
```

Grunden till varför detta är tillagt är att PSI lagen §11 säger att man ska ange avgift och beräkningsgrund. Då range av hasPriceSpecification är klassen gr:PriceSpecification kan man använda properties på den, mest sannolikt bör man använda dct:description, gr:hasCurrency och gr:hasCurrencyValue. Eventuellt bör man också uttrycka gr:validThrough.

Specifikationen bör vara mer specifik kring vilka properties som ska användas på gr:PriceSpecification. Det bör också förtydligas vilka av subklasserna som är aktuella att använda:

- gr:UnitPriceSpecification
- gr:PaymentChargeSpecification
- gr:DeliveryChargeSpecification

Läs mer på [Good relations sida](http://purl.org/goodrelations/v1#).

I Danmark har man valt en enklare lösning med en enkel ja eller nej om det finns avgifter.
Propertyn heter där: http://terms.digst.dk/paymentRequired

**Comment by thomaskvist** [comment]
Jag röstar för den danska varianten. Att hålla prisinformation aktuell på två ställen öppnar för att gammal information ligger kvar.

**Comment by bjornhagstrom** [comment]
Jag lutar åt Thomas håll här. Ja/Nej på avgifter och en länk till mer information tror jag är en bra väg framåt. Risken att metadata kommer vara fel på sikt är väldigt hög då det är jobbigt att hålla den uppdaterad på flera ställen. 

Beräkningarna kan också vara komplexa och omfattande så en egen sida för det kan vara bra.

**Comment by matekh** [comment]
Håller med Thomas!

**Comment by matthiaspalmer** [comment]
Good relations har inkorporerats i schema.org. Där finns en klass schema:Offer som är rätt ok.
Se förslaget här: https://diggsweden.github.io/DCAT-AP-SE/sv/#dcat_Dataset-schema_offers

Väsentligen är förslaget att om man tar betalt så ska man:

1. Peka ut en schema:Offer instans från datamängden via propertyn schema:offers.
2. Instansen måste vara typad som schema:Offer
3. Instansen måste ha en schema:description där man berättar kort om avgiften, beräkningsgrund osv.
4. Det är också rekommenderat att peka till en webbsida som mer omfattat berättar om avgiften. 

I denna modell behöver man alltså inte ange det exakta priset i metadatan utan kan skriva något allmänt och typ säga "för uppdaterad information om avgifter se webbsidan".
