### ISSUE TITLE
Utgivare och producent

### ISSUE THREAD

**Issue by bjornhagstrom** [DIGGSweden/DCAT-AP-SE#42]
På dagens möte om specifikationen pratade vi om de båda rollerna och hur de förhåller sig till varandra och det är inte helt självklart. Ulrika hade ett förslag som jag gillade men när jag kollar i specen ser jag att jag missförstod eller så fungerar det helt enkelt inte. Utmaningen består i att utgivare kan tolkas som den org som har regeringsuppdraget att data samlas in eller så kan det vara den organisation som upprättar data (kan vara en annan org än den som har regeringsuppdraget). Till exempel så samlar SMHI in och publicerar en del data på Naturvårdsverkets uppdrag. Vem är då utgivare?

Jag uppfattade Ulrika som att utgivare på datamängd skulle vara Naturvårdsverket och på distributioner skulle det stå SMHI men utgivare och producent finns inte på distributionsnivå. Kan det vara så att NV skulle så för katalogen och SMHI för datamängden Ulrika?

**Comment by UlrikaDMattsson** [comment]
Naturvårdsverket är ansvarig organisation för alla våra datamängder. Det är en rätt klurig fråga som vi har utrett internt med jusrister och datavärdsjurister. Det datavärden gör (lagrar, tillhandahåller etc) gör de för Naturvårdsverkets räkning. Datamängderna ska därför tas upp i Naturvårdsverkets PSI-förteckning (inte i datavärdens) på samma sätt som det är Naturvårdsverket som ansvarar för att de rapporterna som omfattas av e-plikt levereras till Kungliga biblioteket, att göra informationssäkerhetsklassning mm. Om man väljer att kalla det för utgivare bör det alltså stå i texten att utgivare motsvarar ansvarig organisation (den som har regeringsuppdraget/uppgiften/ myndighetsinstruktionen/verksamhetsansvaret/legaliteten). Naturvårdsverket har informationsägare internt för de datamängder som lagras hos datavärd.

**Comment by UlrikaDMattsson** [comment]
Vad gäller insamling av data har vi andra avtal, utförare som samlar in data för Naturvårdsverkets räkning och sedan levererar dessa till datavärd. Dessa kan nämnas i fritext men brukar inte nämnas i metadataposten. Exempel  luftkvalitetsdata där data samlas in av kommuner, lst, NV mfl  och SMHI tillhandahåller tjänsten samt lagrar data för Naturvårdsverkets räkning. NV har ansvaret enligt bestämmelserna i luftkvalitetsförordningen (SFS 2010:477) och Naturvårdsverkets föreskrifter om kontroll av luftkvalitet (NFS 2016:9).

**Comment by UlrikaDMattsson** [comment]
stryk "samt lagrar data" i förra kommentaren - kan man inte editera i sina tidigare kommentarer?

**Comment by matthiaspalmer** [comment]
En rekommendation är skriven om detta:
https://diggsweden.github.io/DCAT-AP-SE/docs/recommendations.html#9-utgivare-producent-och-andra-akt%C3%B6rsroller
