### ISSUE TITLE
Obligatorisk licens på datamängd / distribution

### ISSUE THREAD

**Issue by matthiaspalmer** [DIGGSweden/DCAT-AP-SE#6]
DCAT-AP säger att dcterms:licens är rekommenderad på distributionen.

Licens är ett av de viktigaste fälten för den som ska besluta om den kan vidareutnyttja en datamängd. Då mindre än hälften av alla distributioner saknar licens kan det vara en poäng att förtydliga hur viktig den är och kräva den.

**Comment by kristineulander** [comment]
Detta krav blir väl problematiskt om en datamängd är begränsad genom att en användare behöver sluta t.ex ett avtal för att nyttja den

**Comment by matthiaspalmer** [comment]
Här tror jag vi behöver hjälp av någon med juridisk kompetens för att avgöra vad som är avtal och vad som är licens. Min gissning är att man köper / ingår ett avtal för att en viss licens ska applicera för sig själv / sin organisation. Licensen förtydligar under vilka villkor man sen får använda det man köpt, t.ex. får man oftast inte återpublicera eller sprida det man köpt hur som helst. 

Kollade igenom [villkoren från Lantmäteriet kring avgifter](https://www.lantmateriet.se/globalassets/kartor-och-geografisk-information/geodataprodukter/avgifter_och_leveransinformation_for_geodata.pdf). I det dokumentet talas det tydligt om licensavgifter och på andra ställen står det att det finns köpevillkor man måste acceptera.

Huruvida det länkade dokumentet ovan eller köpevillkoren är att betrakta som en licens som man kan peka på via dct:license är för mig oklart.

Notera att en framkomlig väg kanske skulle vara att enbart kräva en dct:license på distributionen, dvs när det finns en tydlig digital representation som man kan komma åt. Om man har en datamängd som bara är beskriven att den finns, men att "kontakta oss om ni vill komma åt den så skriver vi avtal", då finns sannolikt ingen distribution och ett obligatoriskt krav om licens skulle inte applicera.
