### ISSUE TITLE
Korrigera About URL till DCAT-AP dokumentation

### ISSUE THREAD

**Issue by mattiasaxell** [DIGGSweden/DCAT-AP-SE#77]
@matthiaspalmer Kan du ändra under "About" (Project Settings) för detta repo: https://github.com/DIGGSweden/DCAT-AP-SE ?

Från URL (som returnerar "Not Found"): 
https://docs.dataportal.se/dcat/main 

Till korrekt URL: 
https://docs.dataportal.se/dcat/

Då kan personer dirigeras korrekt till DIGG:s dokumentation om DCAT-AP.

**Comment by matthiaspalmer** [comment]
Fixat!
