### ISSUE TITLE
Länkar till del på sida fungerar inte som väntat

### ISSUE THREAD

**Issue by bjornhagstrom** [DIGGSweden/DCAT-AP-SE#81]
Jag klickade mig fram till https://docs.dataportal.se/dcat/sv/#dcat_Catalog-dcterms_license men när man skickar den med epost till någon så kommer man överst på sidan, inte till licens för katalogen. Går det att fixa till?

**Comment by matthiaspalmer** [comment]
Tror detta är fixat nu.
Vad jag lyckats reda ut var det enbart ett problem när man valde att öppna en länk i en ny tab.
Du får återöppna ärendet om problemet består.
