### ISSUE TITLE
Klargör i specifikationen för vilka textvärden som språk förväntas

### ISSUE THREAD

**Issue by matthiaspalmer** [diggsweden/DCAT-AP-SE#84]
I dagsläget beskriver [rekommendation 12 när man ska tillhandahålla en språkangivelse för en text](https://docs.dataportal.se/dcat/docs/recommendations/#12-sprakangivelse). Det vore kanske lämpligt i en framtida version av specifikationen att lägga till information om detta direkt i specifikationsdokumentet.

**Comment by salgo60** [comment]
Borde man inte vara tydlig att man skall jobba i riktning [semantisk interoperabilitet](https://en.wikipedia.org/wiki/Semantic_interoperability) och begära att det anges   -  eller finns detta men används inte? Tycker det känns 1980 att prata om att datat presenteras bara på ett språk och inte är språkoberoende...

Jag skrev en artikel i veckan hur vi skapar semantisk interoperabilitet med svenska Litteraturbanken, böcker från tidigt 1900-tal och verk från 1750 där dom redan 1750 insåg vikten av persistenta unika identifierare för runstenar (något jag tjatat om för dataset [länk](https://community.entryscape.com/t/persistenta-identifierare-versionshantering-maste-finnas-i-dataset-som-kallas-oppen-data/379))

* "[Dataroundtripping Wikidata - Wikicommons - Runestones pictures](https://meta.wikimedia.org/wiki/Structured_data_for_GLAM-Wiki/Roundtripping/KMB)"

![image](https://user-images.githubusercontent.com/14206509/114388642-403aea00-9b94-11eb-8347-f1b3c09f6d9a.png)

**Comment by kristineulander** [comment]
Just språkangivelse för själva metadatan är ett krav för att i sin tur möta krav i lagen om digital offentlig service. Behovet handlar om en person med en uppläsningsmaskin använder Sveriges dataportal behöver språkangivelse finnas, annars kommer uppläsningen inte fungera på ett bra sätt. Eftersom dataportalen synliggör metadata som publiceras av andra tar vi fram rekommendationer och krav för denna metadata. 

Absolut är semantisk interoperabilitet i data prioriterade frågor. Just i detta github-repo har vi ärenden som rör just metadataspecifikationen. Relaterat till dina kommentarer kan verksamheter i metadataspecifikationen peka ut unik idenfierare t.ex URI [här](https://docs.dataportal.se/dcat/sv/#dcat_Dataset-dcterms_identifier)

**Comment by salgo60** [comment]
visa gärna med exempel jag tror ni springer åt fel håll.  

`Datamängdens huvudsakliga identifikator, t.ex. en URI eller annan unik identifierare i katalogens sammanhang.`
känns mer att ha en unik identifierare för datamängden vilket är lika viktigt

**Comment by matthiaspalmer** [comment]
Det står tydligt i specifikationen i dagsläget att värdemängden är `Sträng med språk` när så är fallet. Det borde vara tydligt nog.

**Comment by salgo60** [comment]
> Sträng med språk när så är fallet

* ni kan inte låta varje dataleverantör och konsument skapa egna textsträngar det blir kaos se exempel det som levereras till EDP blir "fulöversatt" **det är inte seriöst**
   * börja skapa kunskapsgrafer modell Wikidata är min tro

Dagens svenska data i EDP efter att dataportalen funnits > 10 år

![image](https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/fda37576-cf9c-4a2e-9b7e-cb4fe9b5b160)

 
Tror jag inte sett ett enda dataset med språktag som levererats det måste vara obligatoriskt och tydligare...
* Öppna data är till för att konsumera internationellt
* Dagens data omogenhet gör att man inte ser den internationella vinsten
  * se även tramset med EDP som istället för kunskapsgrafer sitter och "fulöversätter" och hittar på "egna" språktaggar som fi-t-sv-t0-mtec se [projektkyrkogården id: 77-4-2 Antipattern: Strings not things](https://github.com/salgo60/DIGG-skuggbacklog/issues/77#issuecomment-1308635367) -  [Dataportalen Väst - skapar 3 silos och skickar skräpdata till EDP](https://github.com/salgo60/ProjectOutdoorGyms/issues/106#issuecomment-1361147844)

**Comment by salgo60** [comment]
**1) Den datamängden har titel angiven på både svenska och engelska med korrekta språktaggar.**
Men EU är väl inte 2 språk? Skall [DCAT-AP-SE](https://github.com/diggsweden/DCAT-AP-SE) fungera så måste ni leverera på alla dom språk som öppna dataportaler ni skickar till stödjer... testa att google översätt tillbaka till svenska hur det blir hos EDP 

**Fråga 1-1:** finns den i svenska dataportalen jag hittar den inte [LÄNK](https://www.dataportal.se/datasets?p=1&q=TIDAHOLM&s=2&t=20&f=&rt=dataset%24esterms_IndependentDataService%24esterms_ServedByDataService&c=false)

<img width="878" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/613053fe-78d7-46fe-94da-885282176977">
 

**2) Jag gjorde just en koll, 97.7% av alla datamängder**

stickprov eller har ni rapporter på [metadata kvaliten](https://www.wikidata.org/wiki/Wikidata:WikiProject_Outdoor_Gyms/CoverageCountry) som vi kan se? 


 **3) Dessutom finns ytterligare titlar som de automatöversatt till andra språk, _det är deras val att de gör det_**

Lyssnar du på min [fråga 2022 där jag hävdar att EDP](https://www.youtube.com/watch?t=3263&v=COBykM5d_cg&feature=youtu.be) (och även Svenska dataportalen) gör fel så **svarar dom** och jag tolkar det som EDP tycker att det är ni lokala länder som är problemet att man inte följer best practise som Google och andra gör med Knowledge Grap / reconciliation... skriver ni nya specar så bör ni peka på vikten av att **datat kommer att skickas till EDP** och skall stödja dom språk dom har **> 20 stycken**

**Det jag ser** 
* Svenska Dataportalen: tycker det är EDPs problem att deras data inte går att översättas till vettiga textsträngar på flera språk
* EDP: måste arbeta långsamt med de olika länderna där exempelvis Kunskapsgrafer är en väg framåt yada yada yada - som jag tolkar att de enskilda länderna som Svenska Dataportalen inte är kompetenta

**4) För min del tycker jag det är helt ok även om jag skulle föredragit att de separarerat det i olika named graphs.**
Testa med Google Translation och översätt dom tillbaka det blir mycket trams.....

* min tro är att få använder detta data som har så dålig kvalite och att det är extremt svårt att navigera när det är så mycket felöversättningar

* bara att hitta alla utegym från EDP men även på svenska dataportalen är en omöjlighet om inte datat städas upp jmf alla registrerade utegym från Wikidata https://w.wiki/AE9x

**4-1) För min del tycker jag det är helt ok även om jag skulle föredragit att de separarerat det i olika named graphs**

* dom har valt hittepå språkkoder som är väl same same att ha olika named graphs, problemet är att översättningarna blir dåliga och _findability_ dålig när vi skickar [ämnesord: utegym/motion/Essunga kommun](https://data.europa.eu/data/datasets/https-catalog-essunga-se-store-1-resource-18?locale=en) 

<img width="612" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/cdf3a020-2a96-4ade-bd62-8639c5afaca2">

* min poäng när jag kollade så var det enormt låg kvalite på de textsträngar som skapas hos EDP --> **saker kan inte användas eller hittas** 

**skall man skapa en DCAT-AP-SE spec som skickas till en europeisk dataportal så måste den levererade kvaliten vara ok**


**5) Men tyvärr har data.europa.eu en annan princip som bygger på att man skapar nya URI:er för alla datamängder. Det är ett beteende som jag personligen tycker illa om, men det är inte förbjudet. Vi driver aktivt ett påverkansarbete för att bevara** 

**Fråga 5: Var kan vi följa detta påverkansarbete.** Loggas inte ärenden så kommer saker som detta aldrig att lösas... 

* som datakonsument kan jag INTE avgöra om det data jag ser är samma version av datamängd på en annan portal se och läs Google Blog "Building Google Dataset Search and Fostering an Open Data Ecosystem"

<img width="1145" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/44c59a94-7ecb-4c50-be72-d2012a8ace9c">


**6) Men tyvärr har data.europa.eu en annan princip som bygger på att man skapar nya URI:er för alla datamängder. Det är ett **

**Fråga 6:** varför kan ni inte hämta tillbaka EDP url:arna  och ha det i svenska daportalens data som sedan kan hämtas av de lokala dataportalerna...


**7) Du har fel i sak och jag saknar stringens, saklighet och fokus kring ämnet i ärendet i din kommentar**

jag tror ni konsulter **biter er själva i foten** när vi nu 2024 sitter med dålig data och specar en DCAT-AP-SE spec där det borde vara tydligt att det mottagaren konsumerar dvs. EDP knappt går att använda och att dom vill ha data > 20 språk. Att bara vifta bort det som det är deras ansvar eller att det är dom som skickar in det till svenska dataportalens ansvar fungerar inte, då får vi i bästa fall svenska/engelska.... och EDP försöker kocka soppa på en spik...

Läs vad [EDP vill ha av er map data kvalitet](https://dataeuropa.gitlab.io/data-provider-manual/data-quality/)

<img width="922" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/be5c98b0-aeeb-4823-b89e-8f0afbefd70a">

 
**8)  men jag säger detta ur ett tidseffektivitetsperspektiv vid arbete med skattefinansierad verksamhet.**

**Nix ingen är mer glad än jag om ni levererar och vågar utmana DIGG kommuner myndigheter.**.. 
* hoppas du inte skyller underleveranserna på mig utan som sagt vågar utmana kommuner/myndigheter/DIGG/konsulter....  

blir bara sorgsen att se projekt som [NSÖD](https://community.dataportal.se/topic/169/projektet-ns%C3%B6d-nationell-skalning-%C3%B6ppna-data) som dag 0 talar om att skala upp och sedan sitter vi nu 2024 med samma laguppställning och samma dåliga data.... Tror det skulle behövas en [Jens Nylander](https://github.com/salgo60/ESV-skuggbacklog/issues/17) som visade på kostnader av allt dålig data 
* intressant att se är vad han gör på 1 år jmf försöken med "[Leverantörsreskontra som öppna data - hur du publicerar](https://community.dataportal.se/topic/238/leverant%C3%B6rsreskontra-som-%C3%B6ppna-data-hur-du-publicerar)" där felet gissar jag är att man specar och specar och inte har kompetens att göra skitjobbet....  utan har en övertro att befintlig organisation skall leverera... **men som sagt det är utanför specen** men intressant hur mycket elände som hittas under alla stenar han lyfter på ;-)

**Comment by matthiaspalmer** [comment]
Appropå fråga 1.1: @salgo60 Tack för att du påpekar att datamängden saknas. Datamängden finns på Västra Götalands portal: https://www.vgregion.se/ov/dataportal-vast/datakatalog/

Men inte på dataportal.se. Det verkar som Tidaholm har två datakataloger i två olika system. Och den som skördas till dataportalen inte har några publika datamängder. Vi kontaktar dem och frågar hur det ska vara.

Fråga 1: Nej, finns inga krav på att tillhandahålla titlar på 20 språk, uppenbart slöseri med tid och resurser. Bättre EDP automatöversätter till de språk man inte tillhandahåller.  Att tillhandahålla på svenska och engelska är en bra kompromiss ur ett svenskt perspektiv, en del kan vilja tillhandahålla mer.

Fråga 2: Nej det finns ingen publik rapport, du kan gå in på enskilda organisationer på admin, eller skriva ett skript mot dumpen här: https://admin.dataportal.se/all.rdf

Fråga 3: Jag förstår inte vad du referar till. Vi leverar länkade data med URI:er nästan överallt. Dvs things istf. strings. De få ställen där det är strängar är för att du måste ha det, t.ex. titlar. Som jag skrev tycker jag det är bra att EDP gör det. Finns ingen konflikt.

Fråga 4 och 4.1 går inte att förstå. Om du inte vet vad named graphs är bör du slå upp det, inte ställa irrelvanta och svårtydbara frågor. Det slösar bådas våran tid.

Fråga 5: Jodå det går att följa, se här: [https://github.com/SEMICeu/DCAT-AP/tree/master/Webinars/10-Mar-2022](https://github.com/SEMICeu/DCAT-AP/tree/master/Webinars/10-Mar-2022) och den resulterande rekommendationen (som jag inte är helt nöjd med) finns här: https://github.com/SEMICeu/DCAT-AP/blob/2.x.y-draft/releases/2.x.y/usageguide-identifiers.md

Fråga 6: Det handlar om prioriteringar och lämplighet, i detta fall är det högst olämpligt. EDP lägger en referens på CatalogRecord nivån via dct:identifier som en sträng... Inte så jag skulle gjort det men bättre än inget.

Fråga 7: Det är ingen som viftar bort något. Men EDP hanterar inte data, bara metadata. Så kritiken som börjar med att vi sitter med dålig data och att det är 2024 applicerar inte. Du får ta det i något annat fora. Vi gör det vi ska och mer därtill när det gäller metadata. Sverige kommer sannolikt vara först ut med att införa DCAT-AP3.

Fråga 8: Du får bli hur ledsen du vill över att saker inte är som de borde. Men min roll (och många andras) är att agera professionellt och hjälpa våra myndigheter när de efterfrågar det. I detta fall handlar det om nästa version av DCAT-AP-SE, inget annat. Så vi får försöka hålla oss till ämnet.

Sen vill jag påpeka att mina svar ovan är relativt korta och bemöter det du sagt, inget annat. Inga onödiga bilder eller länkar till saker som inte har med saken att göra. Det gör att det blir betydligt lättare att besvara. Jag uppmanar dig att reflektera över detta om du vill att dina inlägg ska bli lästa och göra en verklig skillnad.

Härmed kommer jag stänga detta ärende då själva frågan är avgjord, dina frågor är besvarade och ingen åtgärd är planerad för DCAT-AP-SE3.

**Comment by salgo60** [comment]
Det är ingen ide att argumentera blir bara tragiskt att en extern konsult som skall få fart på öppen data tycker svenska engelska är ok och DIGG som skall vara en expert myndighet verkar helt sakna visioner eller kunskaper att bygga ekosystem

* har inte mer hänt sedan 2010 då dataportalen starta så kan vi inte förvänta oss att detta skall bli mer effektivt 2024 och 10 år framåt
* tycker ni att automatöversätta data och har tittat hur illa det blir så gissar jag ni inte vill att datat skall användas
   * ni har inte själva försökt hämta data från EDP utan det är pdf specande på svenska som alla pengar går till 

men bara tanken att **svenska engelska är ok när vi har fem lagskyddade minoritetsspråk i vårt land: finska, meänkieli, jiddisch, romani och samiska** och detta skall skickas till en europisk dataportal blir det galet..

* här har ni [SPARQL till EDP](https://github.com/salgo60/DIGG-skuggbacklog/issues/51#issuecomment-1325762896)

<img width="1224" alt="image" src="https://github.com/diggsweden/DCAT-AP-SE/assets/14206509/801b887d-3d00-4629-bf4b-6a457a5ac705">

dvs. det ni ser är **key** dvs. ämnesord som är idag massa textsträngar som **måste vara länkade data** ifall detta skall fungera.... dvs. det är inte bara **datasettet som skall ha länkade data utan även metadatat** gissar att ingen ens orkar reagerar på dina kommentarer visar på hur stort kunskapsglapp det är mellan att kunna leverera bra data och de pdf dokument som skrivs idag.....

**Gissar** att bra metadata från icke svensk talande länder kan vara av intresse.... annars så är hela iden med EDP fel... eller ännu ett **kejsarens nya kläder** där konsulter hejar på dåliga lösningar som inte gör skillnad... 

Nog om detta trams...
* bra att ni visar upp er på GITHUB
* tråkigt att vi inte ser att detta tar fart
* galet att DIGG inte visar att dom är en digital expertmyndighet utan mer som [statskontoret håller fram lägger pengar på externa konsulter](https://www.statskontoret.se/publicerat/publikationer/publikationer-2023/myndighetsanalys-av-myndigheten-for-digital-forvaltning-digg/) som jag inte tycker gör skillnad

* over and out
