### ISSUE TITLE
Länkade nyckelord / begrepp

### ISSUE THREAD

**Issue by kristineulander** [diggsweden/DCAT-AP-SE#86]
Det finns utpekade vokabulärer som stöds i DCAT, bland annat de 13 kategorierna. Idag är nyckelord strängar med språk. 

Är det möjligt och ändamålsenligt för dataportalen att tillåta en "friare" inlänkning av etablerade och maskinläsbara begrepp, men som ligger utanför de som redan finns inbäddade i specen? 

För bakgrund se tråd på dataportalens community: https://community.dataportal.se/topic/102/identifierare-och-relationer/29

**Comment by salgo60** [comment]
Se hur rörigt det blir med att flera kommuner lägger "dataset" som verkar peka på samma API för skolmaten se [notebook](https://github.com/salgo60/open-data-examples/blob/master/Skolmat.se%20API.ipynb)

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/14206509/173001387-e5ebb0b2-35aa-467e-9db8-5f3c20139024.png">

sedan 
* kallas dom olika, har eller inte har kategorier som verkar vara kommunens eget påhitt
* vissa skickas det bara ned svenska namn och det blir en maskinöversättning eller inte
* brist på DOI så man vet att det är samma "data set" på Europa portalen som svenska se samma önskan 2020 https://github.com/DIGGSweden/DCAT-AP-SE/issues/72#issuecomment-653731898

**Comment by salgo60** [comment]
jmf [DCAT-AP-NO](https://data.norge.no/specification/dcat-ap-no#Krav-til-kontrollerte-vokabularer)

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/14206509/201490631-b573ed57-8c24-43dc-8b9c-b8d7a0523c79.png">

* video "[EU Open Data Explained training webinar – DCAT and DCAT-AP training Webinar 3: Advanced user](https://youtu.be/etUu24hNgz4?t=849)"

**Comment by salgo60** [comment]
@kristineulander vad är status på detta? det har varit på bordet nu i 19 månader?

Nu sitter nationell dataverkstad och skriver specar som borde peka på [#51 ](https://github.com/salgo60/DiggUptime/issues/51) - [länk diskussion "Lediga tomter"](https://gitlab.com/sarskilt-viktiga-datamangder/lediga-tomter/-/issues/7#note_1207072068)

<img width="908" alt="image" src="https://user-images.githubusercontent.com/14206509/207310077-bcd5490a-2d24-40cd-8fa0-c5be4f4baacc.png">

**Comment by matthiaspalmer** [comment]
Vi stänger detta ärende då det till viss del är ett duplikat av #23 och även addresseras av #107 och kategoriseringen av HVD.
