### ISSUE TITLE
licens på dataset

### ISSUE THREAD

**Issue by borsna** [diggsweden/DCAT-AP-SE#89]
### Contact Details

olof.olsson@snd.gu.se

### What benefits does the suggestion solve?

Idag ligger licens enligt dokumentationen på `Distribution` och inte på `Dataset`
https://docs.dataportal.se/dcat/sv/

På DCAT så listas license på `Dataset`: https://www.w3.org/TR/vocab-dcat-2/#Class:Dataset

På de resurserna som SND levererar satte vi license på `Distribution` då det inte nämns som ett fält på dcat-ap-se. Verkar dock dom dataportalen inte hittar licenser som sätts på `Distribution` och kollar på övriga dataset så har dom satt licens på dataset så kanske skulle det läggas till i dokumentationen?

### Feature suggestion description

Lägg till `dcterms:license` på `Dataset` så det framgår tydligt i dokumentationen.

**Comment by matthiaspalmer** [comment]
Du har rätt att DCAT tillåter dcterms:license på datamängder. Men varken tidigare eller nuvarande versioner av DCAT-AP listar den under datamängd: [https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset).
Därför har vi inte lagt till den i DCAT-AP-SE specifikationen.

Däremot har vi pga en teknikalitet (förbättrad sökning) valt att kopiera över alla dcterms:license som sätts på dcat:Distribution till datamängden i skördningsteget. Så, licenser som sätts på distributioner ska respekteras. Om så inte sker är det en bugg som bör rapporteras till Digg.

Om det finns tydliga skäl att license ska ligga på datamängd så är det möjligt att ändra det i samband med DCAT-AP-SE3 arbetet. Förtydliga isåfall gärna argumentet här.

**Comment by bjornhagstrom** [comment]
Jag har svårt att se att license bör finnas på datamängdsnivå för själva data. Data finns inte där utan i distributionerna som kan ha olika licenser. Vad skulle licens innebära för en datamängd? Att alla distributioner lyder under den licensen (borde då ärvas ned)?

Att det behövs för sökning är en annan sak och bör lösas om Matthias pratar om ovan tänker jag. Rimligt?

**Comment by borsna** [comment]
Mins inte detaljerna kring detta då det är ~8 månader sedan men tror var att jag försökte stämma av dokumentationen i DCAT-AP-SE jämfört med den metadatan som finns tillgänglig under `Ladda ner metadata som RDF` på landningssidorna på dataportal.se där jag upptäckte att licens även fanns med på datasetet.
 
Att licenserna flyttas upp från distributionerna till dataset för att göra filtreringen möjligt är ju enda lösningen då det är själva sökobjetet.

Helt med på att det är en bra att endast ha licens på distrubutionerna i DCAT-AP(-SE) då det blir mer exakt.

Ärendet kan stängas.
