### ISSUE TITLE
Specifikation bör ha länk till repo på GitHub

### ISSUE THREAD

**Issue by bjornhagstrom** [diggsweden/DCAT-AP-SE#93]
### What benefits does the suggestion solve?

Det är svårt att hitta hit och ge förslag på förändringar från https://docs.dataportal.se/dcat/sv/

### Feature suggestion description

Lägg till en länk till detta repo från https://docs.dataportal.se/dcat/sv/

**Comment by salgo60** [comment]
Känns inte som detta rep är aktivt...

**Comment by janderssonse** [comment]
Hej, kan inte svara på detta projekts specifika planer nu direkt, men generellt så, så som en av de GitHub-ansvariga kommer vi iaf att göra en översyn av de projekt som är publika "snart" på diggsweden , och de som inte har Maintainer aktiva eller en förvaltningsplan av något slag kommer att arkiveras som publika.

**Comment by matthiaspalmer** [comment]
Detta projekt har och kommer sannolikt fortsätta ha omväxlande vilande i perioder med aktiv utveckling.
Nuvarande planerna är att inom näraste månaderna göra en minor release för att därefter påbörja ett större arbete för att ta fram DCAT-AP-SE 3.0.0.

Huruvida det är lämpligt att göra mindre ändringar mellan major/minor releases är något som diskuteras. Det förslag som ligger på bordet är att vi ska kunna göra patch-releases löpande av enklare karaktär, typiskt enklare formattering / stavfel och korrigeringar. Eventuellt hamnar vi där efter nästa minor release.

**Comment by salgo60** [comment]
> Detta projekt har och kommer sannolikt fortsätta ha omväxlande vilande i perioder med aktiv utveckling.

Försök att hitta en mall och beskriv projekten/repro på samma sätt så vi ser om projekten 
* drivs av DIGG eller inte
  * om konsulter betalas av DIGG och har en roll var tydlig med det så man vet om man kan kontakta dom och få svar på frågor...
  * om personer som Kristine slutar vem tar gennes roll...
* vad som ligger i en priorierad backlog eller inte
* vem man kan kontakta med telefonnummer 
* om saker inte hamnar i prioriterad backlog refererar till var de hamnar
  * vi ser nu att [kommuner/kommunkoder ältas år efter år](https://gitlab.com/sarskilt-viktiga-datamangder/diariefoerda-handlingar/-/issues/5#note_1620494164) och syns inte tydligt i en backlog där någon tar tag i det
  * vi ser att det pratas [persistenta identifierare](https://github.com/diggsweden/persistent-identifiers-investigation) men inte [5 star data](https://github.com/salgo60/DIGG-skuggbacklog/issues/85) och/eller [reconciliation services](https://github.com/diggsweden/persistent-identifiers-investigation/issues/20)

**Comment by salgo60** [comment]
Visa gärna när ni stänger saker vad ni gjort

**Comment by salgo60** [comment]
> Hej, kan inte svara på detta projekts specifika planer nu direkt, men generellt så, så som en av de GitHub-admins här, kommer vi iaf att göra en översyn av de projekt som är publika "snart" på diggsweden - en hel del har redan arkiverats, och de som inte har Maintainer aktiva eller en förvaltningsplan av något slag kommer att arkiveras som publika.

Ytterliggare exempel hur rörigt det kan bli med DIGG medarbetare som slutar [Med bidrag från "Kristine Ulander - Myndigheten för digital förvaltning"](https://github.com/diggsweden/DCAT-AP-SE/issues/113)
